#!/usr/bin/env bash
# PreToolUse hook: refuse a git push that would introduce a NEW
# 04-AUDITS/validate-registers.py failure.
#
# Wired in .claude/settings.json under hooks.PreToolUse with matcher "Bash".
# Contract (Claude Code hooks reference):
#   - stdin carries the hook payload as JSON, including tool_name and tool_input
#   - exit 0 with no stdout  -> no decision; normal permission flow applies
#   - stdout {"hookSpecificOutput":{"hookEventName":"PreToolUse",
#             "permissionDecision":"deny","permissionDecisionReason":"..."}}
#     -> the tool call is blocked and Claude is shown the reason
#
# The gate this enforces is CLAUDE.md's: a VERIFIED row that no logged
# retrieval backs must not reach the branch, and the branch is the checkpoint.
#
# BASELINE GATE (changed 2026-09-07; was an absolute gate).
# The gate used to block on any failure at all. The tree carries 53 failures
# that no session introduced and that the owner has not yet ruled on, so every
# session was reaching for the documented override on its first push — which
# made the override routine and the gate meaningless. It now blocks only on a
# failure that is not recorded in 04-AUDITS/validator-baseline.json.
#
#   a new defect blocks; the recorded set does not.
#
# A failure matches the baseline on file -> row_id -> failure_type, and on an
# exact match of the offending value (`detail`). Keying on the register's own
# identifier rather than on a line number is what makes the excuse survive an
# insertion above the row. The baseline is written by hand and is never
# regenerated by this hook: a gate that re-records its own baseline before
# every push excuses everything and is worth nothing.
#
# Fail-closed: if the baseline is missing, unreadable or malformed, this hook
# reverts to the absolute gate rather than letting every failure through.
#
# Override, for a new failure that is known, recorded, and deliberately not
# being fixed in the current session: write the push as
#
#     MELAKEELA_REGISTER_GATE=off git push -u origin <branch>
#
# The marker is read out of the command text itself, not out of the hook's
# environment — a PreToolUse hook runs in Claude Code's environment, before the
# command does, so an exported variable would be invisible to it. Putting the
# marker in the command is also the better record: the override is visible in
# the transcript and in the tool call, per push, and every use of it is stated
# in the pull request with the reason. With the baseline gate in place the
# override should now be rare; reaching for it on a failure this session
# introduced is the wrong move. Weakening the validator, or widening the
# baseline to cover your own new failure without saying so, is not an
# available move either.
set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
VALIDATOR="$ROOT/04-AUDITS/validate-registers.py"
BASELINE="$ROOT/04-AUDITS/validator-baseline.json"

PAYLOAD="$(cat)"

decision=$(ROOT="$ROOT" VALIDATOR="$VALIDATOR" BASELINE="$BASELINE" \
           python3 - "$PAYLOAD" <<'PY'
import json, os, re, subprocess, sys

try:
    payload = json.loads(sys.argv[1])
except (ValueError, IndexError):
    sys.exit(0)                      # unparseable payload: express no opinion

if payload.get("tool_name") != "Bash":
    sys.exit(0)

command = (payload.get("tool_input") or {}).get("command") or ""

# Declared override, read out of the command text. See the header.
if re.search(r"(?<![\w-])MELAKEELA_REGISTER_GATE=off(?![\w-])", command):
    sys.exit(0)

# Match only a segment whose *leading token* is git (after optional inline
# environment assignments), so that the literal text appearing inside a quoted
# string, a heredoc body or a comment does not trip the gate. A push smuggled
# through a shell variable or an alias is out of scope: this is a guard rail,
# not a sandbox.
SEGMENT = re.compile(r"&&|\|\||;|\||\n")
LEADING_GIT = re.compile(
    r"""^\s*                       # leading whitespace
        (?:\w+=[^\s]*\s+)*         # inline VAR=value assignments
        (?:command\s+|exec\s+)?    # a couple of common wrappers
        git\b""",
    re.VERBOSE,
)
PUSH_VERB = re.compile(r"(?<![\w-])push(?![\w-])")

blocked = False
for segment in SEGMENT.split(command):
    if LEADING_GIT.match(segment) and PUSH_VERB.search(segment):
        blocked = True
        break

if not blocked:
    sys.exit(0)

validator = os.environ["VALIDATOR"]
if not os.path.exists(validator):
    sys.exit(0)                      # nothing to enforce

proc = subprocess.run(
    [sys.executable, validator, "--json"],
    cwd=os.environ["ROOT"], capture_output=True, text=True,
)
if proc.returncode == 0:
    sys.exit(0)                      # registers clean: defer to normal flow

try:
    failures = json.loads(proc.stdout)
except ValueError:
    # The validator could not produce structured output. Do not guess which
    # failures are new; block on all of them and say why.
    failures = None

def deny(reason):
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)

FOOTER = (
    "CLAUDE.md: a VERIFIED row is backed by a logged retrieval event, its "
    "source_id resolves to 02-SOURCES/access-ledger.csv, and every D- "
    "reference resolves to a row in 09-DECISIONS/OWNER-DECISIONS.csv. Fix "
    "the rows, or record the disagreement as an owner decision, before "
    "pushing. Do not weaken the validator to get past this, and do not add "
    "your own new failure to 04-AUDITS/validator-baseline.json to get past "
    "it either.\n\n"
    "If a NEW failure here is known, recorded and deliberately not being "
    "fixed in this session, set MELAKEELA_REGISTER_GATE=off on the one push "
    "command — and say so, and why, in the pull request."
)

def render(records, limit=20):
    lines = ["  " + r["message"] for r in records]
    head, rest = lines[:limit], lines[limit:]
    detail = "\n".join(head)
    if rest:
        detail += f"\n  ... and {len(rest)} more"
    return detail

if failures is None:
    raw = [ln for ln in proc.stdout.splitlines() if ln.strip()][:20]
    deny("Push blocked: 04-AUDITS/validate-registers.py is failing and its "
         "--json output could not be parsed, so new failures cannot be told "
         "apart from the recorded baseline. Blocking on all of them.\n\n"
         + "\n".join(raw) + "\n\n" + FOOTER)

# --- baseline ---------------------------------------------------------
# entries: {file: {row_id: {failure_type: {"detail": ..., ...}}}}
baseline, baseline_error = {}, None
try:
    with open(os.environ["BASELINE"], encoding="utf-8") as f:
        doc = json.load(f)
    entries = doc.get("entries")
    if not isinstance(entries, dict):
        raise ValueError("no `entries` object")
    baseline = entries
except FileNotFoundError:
    baseline_error = "04-AUDITS/validator-baseline.json is missing"
except (ValueError, OSError) as exc:
    baseline_error = f"04-AUDITS/validator-baseline.json is unreadable: {exc}"

if baseline_error:
    # Fail closed. A gate that opens when its baseline disappears is not a gate.
    deny(f"Push blocked: {baseline_error}, so the recorded failure set cannot "
         "be read and every failure has to be treated as new. This is the "
         "absolute gate, reverted to on purpose.\n\n"
         f"{render(failures)}\n\n{FOOTER}")

def excused(rec):
    entry = (baseline.get(rec["file"], {})
                     .get(rec["row_id"], {})
                     .get(rec["failure_type"]))
    if not isinstance(entry, dict):
        return False
    # Same row, same rule, but a different offending value is a different
    # failure: the cell has been edited since the owner saw it.
    return entry.get("detail", "") == rec["detail"]

new = [r for r in failures if not excused(r)]
if not new:
    sys.exit(0)                      # only recorded failures: let the push run

n_excused = len(failures) - len(new)
deny(
    f"Push blocked: {len(new)} register failure(s) not in "
    "04-AUDITS/validator-baseline.json.\n\n"
    f"{render(new)}\n\n"
    f"({n_excused} other failure(s) are recorded in the baseline and are not "
    "blocking this push. The gate is a baseline gate: a new defect blocks, "
    "the recorded set does not — so what is listed above is this session's "
    "to answer for.)\n\n"
    + FOOTER
)
PY
)

status=$?
if [ $status -ne 0 ]; then
  exit 0                             # a hook failure never blocks work silently
fi

if [ -n "$decision" ]; then
  printf '%s\n' "$decision"
fi
exit 0
