#!/usr/bin/env python3
"""
Which DEDR digitizations are independent of which?

04-AUDITS/domain-e-dedr-digitisation-check.py compared TWO tables and found
10.3% disagreement (IC-E-001), and read the published Brahui figure of
the-northwest-cousin.html against one of them (IC-E-002). It did not ask
whether the two are independent, and JAMBU ships a THIRD table that the
comparison never touched.

This script answers the independence question from JAMBU's own README and
measures the third table. Constitution step 5: two citations tracing to one
upstream count as one.

JAMBU README lines 135-137, verbatim:
  - data/dedr/dedr.csv       <- a SQL database "scraped from the online
                                version", supplied by Suresh, dump dated
                                Oct 2013. "These are now deprecated."
  - data/dedr/dedr_new.csv   <- generated by data/dedr/parse.py, which
                                scrapes https://dsal.uchicago.edu/cgi-bin/
                                app/burrow_query.py over 514 pages.

Both therefore trace to the SAME upstream, the DSAL online DEDR. They are
two scrapes of one website about thirteen years apart, not two readings of
the printed dictionary. Their agreement measures the stability of that
website, not the accuracy of either against Burrow and Emeneau.

Source: moli-mandala/data @ dbae310 (SRC-060, SRC-061)
Usage: dedr-lineage-check.py [JAMBU_ROOT] [OUT_CSV]
"""
import csv, sys, collections

ROOT = sys.argv[1] if len(sys.argv) > 1 else "/tmp/jambu"
OUT  = sys.argv[2] if len(sys.argv) > 2 else "04-AUDITS/dedr-lineage-check.csv"

# dedr.csv spells the language out; dedr_new.csv abbreviates.
MAP = {"Tamil": "Tam", "Malayalam": "Mal", "Kota": "Kota", "Toda": "Toda",
       "Kannada": "Kannada", "Kodagu": "Kodagu", "Tulu": "Tulu",
       "Telugu": "Telugu", "Kolami": "Kolami", "Naikri": "Naikri",
       "Parji": "Parji", "Konda": "Konda", "Pengo": "Pengo", "Kui": "Kui",
       "Kuwi": "Kuwi", "Kurux": "Kurux", "Malto": "Malto", "Manda": "Manda"}

old = collections.defaultdict(set)          # the 2013 SQL dump, deprecated
for r in csv.reader(open(f"{ROOT}/data/dedr/dedr.csv", encoding="utf-8")):
    if len(r) < 4:
        continue
    n = r[1].strip()
    if n.isdigit():
        old[r[3].strip().strip("'")].add(int(n))

new = collections.defaultdict(set)          # the 2026 HTML re-parse, current
for r in csv.reader(open(f"{ROOT}/data/dedr/dedr_new.csv", encoding="utf-8")):
    if len(r) < 3:
        continue
    n = r[1][1:]
    if n.isdigit():
        new[r[0]].add(int(n))

rows, oo, no, sh = [], 0, 0, 0
for o_lab, n_lab in MAP.items():
    a, b = old[o_lab], new[n_lab]
    x, y, z = len(a - b), len(b - a), len(a & b)
    oo, no, sh = oo + x, no + y, sh + z
    rows.append([o_lab, len(a), len(b), x, y, z,
                 round(100.0 * (x + y) / max(1, x + y + z), 1)])

ob, nb = old["Brahui"], new["Brah"]
ot, nt = old["Tamil"],  new["Tam"]

with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL)
    w.writerow(["language", "dedr_csv_entries", "dedr_new_csv_entries",
                "dedr_csv_only", "dedr_new_csv_only", "shared",
                "disagreement_pct"])
    w.writerows(rows)
    w.writerow(["Brahui", len(ob), len(nb), len(ob - nb), len(nb - ob),
                len(ob & nb),
                round(100.0 * (len(ob - nb) + len(nb - ob)) / len(ob | nb), 1)])
    w.writerow(["TOTAL (18 mapped languages)", "", "", oo, no, sh,
                round(100.0 * (oo + no) / (oo + no + sh), 1)])
    w.writerow(["Brahui roots with a Tamil cognate",
                f"{len(ob & ot)} of {len(ob)} = {round(100.0*len(ob&ot)/len(ob))}%",
                f"{len(nb & nt)} of {len(nb)} = {round(100.0*len(nb&nt)/len(nb))}%",
                "", "", "",
                "site (ArimeKannada lineage) publishes 191 of 262 = 73%"])

for r in rows:
    print(f"  {r[0]:<12} dedr.csv {r[1]:>5}  dedr_new.csv {r[2]:>5}  disagree {r[6]:>5}%")
print(f"\n  TOTAL over 18 languages, WITHIN the DSAL lineage: "
      f"{round(100.0*(oo+no)/(oo+no+sh),1)}% disagreement")
print(f"  (against 10.3% BETWEEN the DSAL lineage and the ArimeKannada one, IC-E-001)")
print(f"\n  Brahui roots with a Tamil cognate")
print(f"    dedr.csv     (DSAL scrape, 2013, deprecated) {len(ob&ot)} of {len(ob)} "
      f"= {round(100.0*len(ob&ot)/len(ob))}%")
print(f"    dedr_new.csv (DSAL scrape, 2026, current)    {len(nb&nt)} of {len(nb)} "
      f"= {round(100.0*len(nb&nt)/len(nb))}%")
print(f"    site         (ArimeKannada lineage)          191 of 262 = 73%")
print(f"\n-> {OUT}")
